import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-detail',
  templateUrl: './detail.component.html',
  styleUrls: ['./detail.component.css'],
})
export class DetailComponent implements OnInit {
  bio = {
    person: {
      professionalHeadline: 'Ingeniero de Sistemas',
      completion: 1,
      showPhone: false,
      created: '2020-04-09T13:58:55Z',
      verified: false,
      flags: {
        benefits: true,
        canary: false,
        enlauSource: false,
        fake: false,
        featureDiscovery: false,
        getSignaledBenefitsViewed: false,
        firstSignalSent: false,
        promoteYourselfBenefitsViewed: false,
        promoteYourselfCompleted: false,
        importingLinkedin: false,
        onBoarded: true,
        opportunitiesNotificationsSent: true,
        remoter: true,
        signalsFeatureDiscovery: false,
        signedInToOpportunities: false,
        importingLinkedinRecommendations: true,
        contactsImported: false,
      },
      weight: 0,
      locale: 'es',
      subjectId: '161450',
      picture:
        'https://starrgate.s3.amazonaws.com:443/users/0bb0ba8d8cad4685b403eae98385f8b1ca3f3864/profile_4xoHxXL.jpg',
      hasEmail: true,
      name: 'Cristhian Barros',
      links: [
        {
          id: 'mjlDwqjZ',
          name: 'github',
          address: 'https://cristhianbarros.github.io/',
        },
        {
          id: 'pydvDYMP',
          name: 'linkedin',
          address: 'https://www.linkedin.com/in/cristhian-barros-35288310b/',
        },
        {
          id: '5ykW7myQ',
          name: 'github',
          address: 'https://github.com/cristhianbarros',
        },
      ],
      location: {
        name: 'Colombia',
        latitude: 4.570868,
        longitude: -74.297333,
        timezone: 'America/Bogota',
        timezoneOffSet: -18000000,
      },
      theme: 'teal400',
      id: 'wM7G2X3M',
      pictureThumbnail:
        'https://starrgate.s3.amazonaws.com:443/CACHE/images/users/0bb0ba8d8cad4685b403eae98385f8b1ca3f3864/profile_4xoHxXL/4ac0074f94bc7172f6db32f65d51ac69.jpg',
      claimant: false,
      weightGraph:
        'https://hcti.io/v1/image/c10c1553-30d6-48f5-b756-4c98c4d2fb7c',
      publicId: 'cristhianb91',
    },
    stats: {
      projects: 3,
      education: 1,
      strengths: 24,
      interests: 3,
    },
    strengths: [
      {
        id: 'qNP07YaN',
        code: 44603,
        name: 'Ionic Framework',
        weight: 0,
        recommendations: 1,
        media: [],
        created: '2020-04-21T02:39:11',
      },
      {
        id: 'Oj6EvEAM',
        code: 21771,
        name: 'Autonomy',
        weight: 0,
        recommendations: 0,
        media: [],
        created: '2020-04-20T00:36:45',
      },
      {
        id: 'BMLWDWVN',
        code: 32590,
        name: 'TypeScript',
        weight: 0,
        recommendations: 0,
        media: [],
        created: '2020-04-20T00:36:45',
      },
      {
        id: 'vy5EWE4y',
        code: 34431,
        name: 'Software Architecture',
        weight: 0,
        recommendations: 1,
        media: [],
        created: '2020-04-20T00:36:45',
      },
      {
        id: 'ANaJmJ1M',
        code: 55192,
        name: 'Attention to detail',
        weight: 0,
        recommendations: 0,
        media: [],
        created: '2020-04-20T00:36:45',
      },
      {
        id: 'Ajrbzbdj',
        code: 55488,
        name: 'Fast Learner',
        weight: 0,
        recommendations: 1,
        media: [],
        created: '2020-04-20T00:36:45',
      },
      {
        id: 'kybbeb7y',
        code: 25720,
        name: 'Web Development',
        weight: 0,
        recommendations: 0,
        media: [],
        created: '2020-04-20T00:36:45',
      },
      {
        id: 'ny1W6WBM',
        code: 55532,
        name: 'Full Stack Development',
        weight: 0,
        recommendations: 0,
        media: [],
        created: '2020-04-20T00:36:45',
      },
      {
        id: 'gMR0x02y',
        code: 56184,
        name: 'Strategic Thinking',
        weight: 0,
        recommendations: 0,
        media: [],
        created: '2020-04-20T00:36:45',
      },
      {
        id: 'eynxQQRM',
        code: 43538,
        name: 'Google Maps API',
        weight: 0,
        recommendations: 0,
        media: [],
        created: '2020-04-20T00:26:54',
      },
      {
        id: 'pyoO44Ay',
        code: 19243,
        name: 'Firebase',
        weight: 0,
        recommendations: 0,
        media: [],
        created: '2020-04-20T00:26:40',
      },
      {
        id: 'Ajrbzzdj',
        code: 55898,
        name: 'Ionic',
        weight: 0,
        recommendations: 0,
        media: [],
        created: '2020-04-20T00:26:32',
      },
      {
        id: 'BMLWDDVN',
        code: 29373,
        name: 'Laravel',
        weight: 0,
        recommendations: 1,
        media: [],
        created: '2020-04-20T00:25:49',
      },
      {
        id: 'Oj6EvvAM',
        code: 6380,
        name: 'API',
        weight: 0,
        recommendations: 0,
        media: [],
        created: '2020-04-20T00:25:44',
      },
      {
        id: 'OMvgbb9j',
        code: 18319,
        name: 'Javascript',
        weight: 0,
        recommendations: 1,
        media: [],
        created: '2020-04-20T00:21:14',
      },
      {
        id: '8jp4zz9j',
        code: 18317,
        name: 'CSS3',
        weight: 0,
        recommendations: 0,
        media: [],
        created: '2020-04-20T00:21:11',
      },
      {
        id: 'bjA7OOvN',
        code: 18318,
        name: 'HTML5',
        weight: 0,
        recommendations: 0,
        media: [],
        created: '2020-04-20T00:21:08',
      },
      {
        id: 'JMekWXay',
        code: 49214,
        name: 'PostgreSQL',
        weight: 0,
        recommendations: 1,
        media: [],
        created: '2020-04-20T00:21:04',
      },
      {
        id: '5ykb9Qaj',
        code: 24450,
        name: 'Android',
        weight: 0,
        recommendations: 0,
        media: [],
        created: '2020-04-13T22:37:01',
      },
      {
        id: '0yz929Vj',
        code: 56436,
        name: 'Liderazgo',
        weight: 0,
        recommendations: 0,
        media: [],
        created: '2020-04-13T22:34:44',
      },
      {
        id: 'RyDgO2Oj',
        code: 56207,
        name: 'Angular',
        weight: 0,
        recommendations: 1,
        media: [],
        created: '2020-04-09T14:01:39',
      },
      {
        id: 'AMW0rv0j',
        code: 32052,
        name: 'PHP',
        weight: 0,
        recommendations: 1,
        media: [],
        created: '2020-04-09T14:01:36',
      },
      {
        id: 'LMgJPwEN',
        code: 55262,
        name: 'Commitment',
        weight: 0,
        recommendations: 0,
        media: [],
        created: '2020-04-09T14:00:57',
      },
      {
        id: '8jpz4LwN',
        code: 704,
        name: 'Software Development',
        weight: 0,
        recommendations: 1,
        media: [],
        created: '2020-04-09T14:00:38',
      },
    ],
    interests: [
      {
        id: 'AjrQ1aGM',
        code: 52274,
        name: 'Software Engineering',
        media: [],
        created: '2020-04-09T14:01:49',
      },
      {
        id: 'kyb0YDKM',
        code: 6217,
        name: 'Project Management',
        media: [],
        created: '2020-04-09T14:01:57',
      },
      {
        id: 'ny1OqevM',
        code: 10062,
        name: 'English',
        media: [],
        created: '2020-04-09T14:02:08',
      },
    ],
    experiences: [
      {
        id: 'KNxz77gj',
        category: 'education',
        name: 'Ingeniería de Sistemas',
        organizations: [
          {
            id: 70417,
            name: 'Institución Universitaria Salazar y Herrera',
          },
        ],
        fromMonth: 'January',
        fromYear: '2013',
        toMonth: 'November',
        toYear: '2016',
        remote: false,
        additionalInfo: '',
        highlighted: true,
        weight: 0,
        verifications: 0,
        recommendations: 0,
        media: [],
      },
      {
        id: 'ny1Q34vy',
        category: 'projects',
        name: 'Carpooling App',
        organizations: [
          {
            id: 193323,
            name: 'Ingeniería Especializada S.A',
          },
        ],
        fromMonth: 'August',
        fromYear: '2019',
        toMonth: 'November',
        toYear: '2019',
        highlighted: true,
        weight: 0,
        verifications: 2,
        recommendations: 1,
        media: [
          {
            group: '0cd81065-aacc-4c57-a9c9-1bbc14240d75',
            mediaType: 'link',
            description: '',
            mediaItems: [
              {
                id: 'WNVaVdyr',
                address:
                  'https://cristhianbarros.github.io/cv/index.html#carpooling-app',
              },
            ],
          },
        ],
      },
      {
        id: 'JyQxYKqj',
        category: 'projects',
        name: 'SIG+ SMG Emails',
        organizations: [
          {
            id: 193323,
            name: 'Ingeniería Especializada S.A',
          },
        ],
        fromMonth: 'March',
        fromYear: '2020',
        toMonth: 'March',
        toYear: '2020',
        highlighted: true,
        weight: 0,
        verifications: 1,
        recommendations: 1,
        media: [
          {
            group: 'f7e2acb4-f3b5-42b1-9f4e-582598b84fd0',
            mediaType: 'link',
            description: '',
            mediaItems: [
              {
                id: 'eynmKWja',
                address:
                  'https://cristhianbarros.github.io/cv/index.html#smg-emails',
              },
            ],
          },
        ],
      },
      {
        id: 'GNKnzDry',
        category: 'projects',
        name: 'BackLog SIG+',
        organizations: [
          {
            id: 193323,
            name: 'Ingeniería Especializada S.A',
          },
        ],
        fromMonth: 'November',
        fromYear: '2012',
        toMonth: '',
        toYear: '',
        highlighted: true,
        weight: 0,
        verifications: 1,
        recommendations: 1,
        media: [],
      },
    ],
    achievements: [],
    jobs: [],
    projects: [
      {
        id: 'ny1Q34vy',
        category: 'projects',
        name: 'Carpooling App',
        organizations: [
          {
            id: 193323,
            name: 'Ingeniería Especializada S.A',
          },
        ],
        fromMonth: 'August',
        fromYear: '2019',
        toMonth: 'November',
        toYear: '2019',
        highlighted: true,
        weight: 0,
        verifications: 2,
        recommendations: 1,
        media: [
          {
            group: '0cd81065-aacc-4c57-a9c9-1bbc14240d75',
            mediaType: 'link',
            description: '',
            mediaItems: [
              {
                id: 'WNVaVdyr',
                address:
                  'https://cristhianbarros.github.io/cv/index.html#carpooling-app',
              },
            ],
          },
        ],
      },
      {
        id: 'JyQxYKqj',
        category: 'projects',
        name: 'SIG+ SMG Emails',
        organizations: [
          {
            id: 193323,
            name: 'Ingeniería Especializada S.A',
          },
        ],
        fromMonth: 'March',
        fromYear: '2020',
        toMonth: 'March',
        toYear: '2020',
        highlighted: true,
        weight: 0,
        verifications: 1,
        recommendations: 1,
        media: [
          {
            group: 'f7e2acb4-f3b5-42b1-9f4e-582598b84fd0',
            mediaType: 'link',
            description: '',
            mediaItems: [
              {
                id: 'eynmKWja',
                address:
                  'https://cristhianbarros.github.io/cv/index.html#smg-emails',
              },
            ],
          },
        ],
      },
      {
        id: 'GNKnzDry',
        category: 'projects',
        name: 'BackLog SIG+',
        organizations: [
          {
            id: 193323,
            name: 'Ingeniería Especializada S.A',
          },
        ],
        fromMonth: 'November',
        fromYear: '2012',
        toMonth: '',
        toYear: '',
        highlighted: true,
        weight: 0,
        verifications: 1,
        recommendations: 1,
        media: [],
      },
    ],
    publications: [],
    education: [
      {
        id: 'KNxz77gj',
        category: 'education',
        name: 'Ingeniería de Sistemas',
        organizations: [
          {
            id: 70417,
            name: 'Institución Universitaria Salazar y Herrera',
          },
        ],
        fromMonth: 'January',
        fromYear: '2013',
        toMonth: 'November',
        toYear: '2016',
        remote: false,
        additionalInfo: '',
        highlighted: true,
        weight: 0,
        verifications: 0,
        recommendations: 0,
        media: [],
      },
    ],
    opportunities: [
      {
        id: 'NmDZgz1y',
        interest: 'jobs',
        field: 'active',
        data: true,
      },
      {
        id: 'MezX6Adj',
        interest: 'jobs',
        field: 'private',
        data: false,
      },
      {
        id: 'jpXeEPJj',
        interest: 'gigs',
        field: 'active',
        data: true,
      },
      {
        id: 'Mv9QnkmN',
        interest: 'gigs',
        field: 'private',
        data: false,
      },
      {
        id: 'yJnk8WEy',
        interest: 'internships',
        field: 'active',
        data: true,
      },
      {
        id: 'MgBzlvmN',
        interest: 'internships',
        field: 'private',
        data: false,
      },
      {
        id: 'N8O6Gr7y',
        interest: 'mentoring',
        field: 'active',
        data: true,
      },
      {
        id: 'yzwnlQQN',
        interest: 'advising',
        field: 'active',
        data: true,
      },
      {
        id: 'MWGWZ2dM',
        interest: 'hiring',
        field: 'active',
        data: false,
      },
      {
        id: 'jAW6md1N',
        interest: 'industries',
        field: 'types',
        data: [
          {
            locale: 'es',
            name: 'Tecnologia',
          },
        ],
      },
    ],
    languages: [
      {
        code: 'es',
        language: 'Español',
        fluency: 'fully-fluent',
      },
      {
        code: 'en',
        language: 'Inglés',
        fluency: 'conversational',
      },
    ],
    personalityTraitsResults: {
      groups: [
        {
          id: 'extraversion',
          order: 0,
          median: 3.5,
          stddev: 0.57,
        },
        {
          id: 'openness-to-experience',
          order: 1,
          median: 3.41,
          stddev: 0.6,
        },
        {
          id: 'conscientiousness',
          order: 2,
          median: 3.44,
          stddev: 0.56,
        },
        {
          id: 'agreeableness',
          order: 3,
          median: 2.94,
          stddev: 0.58,
        },
        {
          id: 'honesty-humility',
          order: 4,
          median: 3.19,
          stddev: 0.62,
        },
        {
          id: 'emotionality',
          order: 5,
          median: 3.43,
          stddev: 0.62,
        },
      ],
      analyses: [
        {
          groupId: 'openness-to-experience',
          analysis: 3.25,
        },
        {
          groupId: 'honesty-humility',
          analysis: 4.44,
        },
        {
          groupId: 'agreeableness',
          analysis: 3.31,
        },
        {
          groupId: 'altruism',
          analysis: 4,
        },
        {
          groupId: 'conscientiousness',
          analysis: 4.25,
        },
        {
          groupId: 'emotionality',
          analysis: 2.94,
        },
        {
          groupId: 'extraversion',
          analysis: 3.88,
        },
      ],
    },
    professionalCultureGenomeResults: {
      groups: [
        {
          id: '1',
          text: 'Achievement oriented',
          answer: 'all-the-time',
          order: 0,
        },
        {
          id: '2',
          text: 'Action oriented',
          answer: 'all-the-time',
          order: 1,
        },
        {
          id: '3',
          text: 'Adaptability',
          answer: 'all-the-time',
          order: 2,
        },
        {
          id: '6',
          text: 'Being analytical',
          answer: 'all-the-time',
          order: 3,
        },
        {
          id: '8',
          text: 'Being careful',
          answer: 'all-the-time',
          order: 4,
        },
        {
          id: '9',
          text: 'Being competitive',
          answer: 'all-the-time',
          order: 5,
        },
        {
          id: '10',
          text: 'Being customer oriented',
          answer: 'all-the-time',
          order: 6,
        },
        {
          id: '11',
          text: 'Being decisive',
          answer: 'all-the-time',
          order: 7,
        },
        {
          id: '13',
          text: 'Being fair',
          answer: 'all-the-time',
          order: 8,
        },
        {
          id: '14',
          text: 'Being honest',
          answer: 'all-the-time',
          order: 9,
        },
        {
          id: '15',
          text: 'Being innovative',
          answer: 'all-the-time',
          order: 10,
        },
        {
          id: '18',
          text: 'Being precise',
          answer: 'all-the-time',
          order: 11,
        },
        {
          id: '21',
          text: 'Being results oriented',
          answer: 'all-the-time',
          order: 12,
        },
        {
          id: '23',
          text: 'Being supportive',
          answer: 'all-the-time',
          order: 13,
        },
        {
          id: '24',
          text: 'Being team oriented',
          answer: 'all-the-time',
          order: 14,
        },
        {
          id: '25',
          text: 'Being tolerant',
          answer: 'all-the-time',
          order: 15,
        },
        {
          id: '26',
          text: 'Being willing to experiment',
          answer: 'all-the-time',
          order: 16,
        },
        {
          id: '28',
          text: 'Cooperative',
          answer: 'all-the-time',
          order: 17,
        },
        {
          id: '29',
          text: 'Emphasis on professional growth',
          answer: 'all-the-time',
          order: 18,
        },
        {
          id: '30',
          text: 'Emphasizing quality',
          answer: 'all-the-time',
          order: 19,
        },
        {
          id: '31',
          text: 'Fast moving',
          answer: 'all-the-time',
          order: 20,
        },
        {
          id: '33',
          text: 'Having high ethical standards',
          answer: 'all-the-time',
          order: 21,
        },
        {
          id: '34',
          text: 'Having high expectations for performance',
          answer: 'all-the-time',
          order: 22,
        },
        {
          id: '35',
          text: 'Having integrity',
          answer: 'all-the-time',
          order: 23,
        },
        {
          id: '38',
          text: 'Learning from mistakes',
          answer: 'all-the-time',
          order: 24,
        },
        {
          id: '39',
          text: 'Listening to customers',
          answer: 'all-the-time',
          order: 25,
        },
        {
          id: '40',
          text: 'Making your numbers',
          answer: 'all-the-time',
          order: 26,
        },
        {
          id: '42',
          text: 'Paying attention to detail',
          answer: 'all-the-time',
          order: 27,
        },
        {
          id: '45',
          text: 'Respecting individuals',
          answer: 'all-the-time',
          order: 28,
        },
        {
          id: '46',
          text: 'Risk-taking',
          answer: 'all-the-time',
          order: 29,
        },
        {
          id: '47',
          text: 'Security of employment',
          answer: 'all-the-time',
          order: 30,
        },
        {
          id: '49',
          text: 'Stability',
          answer: 'all-the-time',
          order: 31,
        },
        {
          id: '50',
          text: 'Taking individual responsibility',
          answer: 'all-the-time',
          order: 32,
        },
        {
          id: '51',
          text: 'Taking initiative',
          answer: 'all-the-time',
          order: 33,
        },
        {
          id: '54',
          text: 'Working in collaboration with others',
          answer: 'all-the-time',
          order: 34,
        },
        {
          id: '4',
          text: 'Avoiding conflict',
          answer: 'most-of-the-time',
          order: 35,
        },
        {
          id: '7',
          text: 'Being calm',
          answer: 'most-of-the-time',
          order: 36,
        },
        {
          id: '12',
          text: 'Being easygoing',
          answer: 'most-of-the-time',
          order: 37,
        },
        {
          id: '17',
          text: 'Being people oriented',
          answer: 'most-of-the-time',
          order: 38,
        },
        {
          id: '19',
          text: 'Being quick to take advantage of opportunities',
          answer: 'most-of-the-time',
          order: 39,
        },
        {
          id: '20',
          text: 'Being reflective',
          answer: 'most-of-the-time',
          order: 40,
        },
        {
          id: '22',
          text: 'Being rule oriented',
          answer: 'most-of-the-time',
          order: 41,
        },
        {
          id: '27',
          text: 'Confronting conflict directly',
          answer: 'most-of-the-time',
          order: 42,
        },
        {
          id: '37',
          text: 'Individual goals are transparent',
          answer: 'most-of-the-time',
          order: 43,
        },
        {
          id: '43',
          text: 'Predictability',
          answer: 'most-of-the-time',
          order: 44,
        },
        {
          id: '16',
          text: 'Being market driven',
          answer: 'sometimes',
          order: 45,
        },
        {
          id: '41',
          text: 'Not being constrained by many rules',
          answer: 'sometimes',
          order: 46,
        },
        {
          id: '44',
          text: "Putting organization's goals before unit's goals",
          answer: 'sometimes',
          order: 47,
        },
        {
          id: '52',
          text: 'Urgency',
          answer: 'sometimes',
          order: 48,
        },
        {
          id: '5',
          text: 'Being aggressive',
          answer: 'rarely',
          order: 49,
        },
        {
          id: '32',
          text: 'Hard-driving',
          answer: 'rarely',
          order: 50,
        },
        {
          id: '48',
          text: 'Sharing information freely',
          answer: 'rarely',
          order: 51,
        },
        {
          id: '36',
          text: 'High levels of conflict',
          answer: 'never',
          order: 52,
        },
        {
          id: '53',
          text: 'What you know matters more than who you know',
          answer: 'never',
          order: 53,
        },
      ],
      analyses: [
        {
          groupId: '1',
          section: 'adaptability',
          analysis: -0.2,
        },
        {
          groupId: '1',
          section: 'integrity',
          analysis: -0.32,
        },
        {
          groupId: '1',
          section: 'collaborative',
          analysis: -0.44,
        },
        {
          groupId: '1',
          section: 'results-oriented',
          analysis: 2.12,
        },
        {
          groupId: '1',
          section: 'customer-oriented',
          analysis: -0.32,
        },
        {
          groupId: '1',
          section: 'detail-oriented',
          analysis: -0.36,
        },
        {
          groupId: '10',
          section: 'adaptability',
          analysis: 0.2,
        },
        {
          groupId: '10',
          section: 'integrity',
          analysis: 0.04,
        },
        {
          groupId: '10',
          section: 'collaborative',
          analysis: 0.28,
        },
        {
          groupId: '10',
          section: 'results-oriented',
          analysis: -0.16,
        },
        {
          groupId: '10',
          section: 'customer-oriented',
          analysis: 3.2,
        },
        {
          groupId: '10',
          section: 'detail-oriented',
          analysis: 0.2,
        },
        {
          groupId: '11',
          section: 'adaptability',
          analysis: -0.36,
        },
        {
          groupId: '11',
          section: 'integrity',
          analysis: -0.04,
        },
        {
          groupId: '11',
          section: 'collaborative',
          analysis: -1.08,
        },
        {
          groupId: '11',
          section: 'results-oriented',
          analysis: 0.36,
        },
        {
          groupId: '11',
          section: 'customer-oriented',
          analysis: 0.32,
        },
        {
          groupId: '11',
          section: 'detail-oriented',
          analysis: -0.48,
        },
        {
          groupId: '12',
          section: 'adaptability',
          analysis: 0.33,
        },
        {
          groupId: '12',
          section: 'integrity',
          analysis: -0.99,
        },
        {
          groupId: '12',
          section: 'collaborative',
          analysis: 1.17,
        },
        {
          groupId: '12',
          section: 'results-oriented',
          analysis: -1.08,
        },
        {
          groupId: '12',
          section: 'customer-oriented',
          analysis: 0.24,
        },
        {
          groupId: '12',
          section: 'detail-oriented',
          analysis: -0.3,
        },
        {
          groupId: '13',
          section: 'adaptability',
          analysis: -0.08,
        },
        {
          groupId: '13',
          section: 'integrity',
          analysis: 1.92,
        },
        {
          groupId: '13',
          section: 'collaborative',
          analysis: 0.28,
        },
        {
          groupId: '13',
          section: 'results-oriented',
          analysis: -1.24,
        },
        {
          groupId: '13',
          section: 'customer-oriented',
          analysis: 0.2,
        },
        {
          groupId: '13',
          section: 'detail-oriented',
          analysis: -0.4,
        },
        {
          groupId: '14',
          section: 'adaptability',
          analysis: 0.04,
        },
        {
          groupId: '14',
          section: 'integrity',
          analysis: 2.68,
        },
        {
          groupId: '14',
          section: 'collaborative',
          analysis: 0.12,
        },
        {
          groupId: '14',
          section: 'results-oriented',
          analysis: -0.16,
        },
        {
          groupId: '14',
          section: 'customer-oriented',
          analysis: -0.24,
        },
        {
          groupId: '14',
          section: 'detail-oriented',
          analysis: 0.16,
        },
        {
          groupId: '15',
          section: 'adaptability',
          analysis: 2.4,
        },
        {
          groupId: '15',
          section: 'integrity',
          analysis: 0.36,
        },
        {
          groupId: '15',
          section: 'collaborative',
          analysis: -0.04,
        },
        {
          groupId: '15',
          section: 'results-oriented',
          analysis: 0.24,
        },
        {
          groupId: '15',
          section: 'customer-oriented',
          analysis: 0.16,
        },
        {
          groupId: '15',
          section: 'detail-oriented',
          analysis: 0.36,
        },
        {
          groupId: '16',
          section: 'adaptability',
          analysis: -0.1,
        },
        {
          groupId: '16',
          section: 'integrity',
          analysis: -0.32,
        },
        {
          groupId: '16',
          section: 'collaborative',
          analysis: -0.14,
        },
        {
          groupId: '16',
          section: 'results-oriented',
          analysis: 0.18,
        },
        {
          groupId: '16',
          section: 'customer-oriented',
          analysis: 1.04,
        },
        {
          groupId: '16',
          section: 'detail-oriented',
          analysis: -0.46,
        },
        {
          groupId: '17',
          section: 'adaptability',
          analysis: 0.06,
        },
        {
          groupId: '17',
          section: 'integrity',
          analysis: 0.03,
        },
        {
          groupId: '17',
          section: 'collaborative',
          analysis: 0.27,
        },
        {
          groupId: '17',
          section: 'results-oriented',
          analysis: -0.03,
        },
        {
          groupId: '17',
          section: 'customer-oriented',
          analysis: 0.6,
        },
        {
          groupId: '17',
          section: 'detail-oriented',
          analysis: -1.35,
        },
        {
          groupId: '18',
          section: 'adaptability',
          analysis: -1.08,
        },
        {
          groupId: '18',
          section: 'integrity',
          analysis: -0.32,
        },
        {
          groupId: '18',
          section: 'collaborative',
          analysis: -0.56,
        },
        {
          groupId: '18',
          section: 'results-oriented',
          analysis: -0.32,
        },
        {
          groupId: '18',
          section: 'customer-oriented',
          analysis: -0.48,
        },
        {
          groupId: '18',
          section: 'detail-oriented',
          analysis: 2.48,
        },
        {
          groupId: '19',
          section: 'adaptability',
          analysis: 1.38,
        },
        {
          groupId: '19',
          section: 'integrity',
          analysis: -1.02,
        },
        {
          groupId: '19',
          section: 'collaborative',
          analysis: -0.57,
        },
        {
          groupId: '19',
          section: 'results-oriented',
          analysis: -0.03,
        },
        {
          groupId: '19',
          section: 'customer-oriented',
          analysis: 0.45,
        },
        {
          groupId: '19',
          section: 'detail-oriented',
          analysis: -0.24,
        },
        {
          groupId: '2',
          section: 'adaptability',
          analysis: -0.16,
        },
        {
          groupId: '2',
          section: 'integrity',
          analysis: -0.68,
        },
        {
          groupId: '2',
          section: 'collaborative',
          analysis: -0.28,
        },
        {
          groupId: '2',
          section: 'results-oriented',
          analysis: 0.48,
        },
        {
          groupId: '2',
          section: 'customer-oriented',
          analysis: -0.2,
        },
        {
          groupId: '2',
          section: 'detail-oriented',
          analysis: -0.96,
        },
        {
          groupId: '20',
          section: 'adaptability',
          analysis: -0.06,
        },
        {
          groupId: '20',
          section: 'integrity',
          analysis: -1.32,
        },
        {
          groupId: '20',
          section: 'collaborative',
          analysis: -1.17,
        },
        {
          groupId: '20',
          section: 'results-oriented',
          analysis: -0.03,
        },
        {
          groupId: '20',
          section: 'customer-oriented',
          analysis: -0.69,
        },
        {
          groupId: '20',
          section: 'detail-oriented',
          analysis: 0.03,
        },
        {
          groupId: '21',
          section: 'adaptability',
          analysis: -0.48,
        },
        {
          groupId: '21',
          section: 'integrity',
          analysis: -0.4,
        },
        {
          groupId: '21',
          section: 'collaborative',
          analysis: -0.48,
        },
        {
          groupId: '21',
          section: 'results-oriented',
          analysis: 2.4,
        },
        {
          groupId: '21',
          section: 'customer-oriented',
          analysis: 0.44,
        },
        {
          groupId: '21',
          section: 'detail-oriented',
          analysis: -0.48,
        },
        {
          groupId: '22',
          section: 'adaptability',
          analysis: -1.89,
        },
        {
          groupId: '22',
          section: 'integrity',
          analysis: -0.36,
        },
        {
          groupId: '22',
          section: 'collaborative',
          analysis: -0.33,
        },
        {
          groupId: '22',
          section: 'results-oriented',
          analysis: 0.15,
        },
        {
          groupId: '22',
          section: 'customer-oriented',
          analysis: -0.15,
        },
        {
          groupId: '22',
          section: 'detail-oriented',
          analysis: 0.33,
        },
        {
          groupId: '23',
          section: 'adaptability',
          analysis: -0.28,
        },
        {
          groupId: '23',
          section: 'integrity',
          analysis: 0.68,
        },
        {
          groupId: '23',
          section: 'collaborative',
          analysis: 1.76,
        },
        {
          groupId: '23',
          section: 'results-oriented',
          analysis: -1.44,
        },
        {
          groupId: '23',
          section: 'customer-oriented',
          analysis: -0.12,
        },
        {
          groupId: '23',
          section: 'detail-oriented',
          analysis: -0.04,
        },
        {
          groupId: '24',
          section: 'adaptability',
          analysis: 0.08,
        },
        {
          groupId: '24',
          section: 'integrity',
          analysis: 0.48,
        },
        {
          groupId: '24',
          section: 'collaborative',
          analysis: 2.6,
        },
        {
          groupId: '24',
          section: 'results-oriented',
          analysis: 0.4,
        },
        {
          groupId: '24',
          section: 'customer-oriented',
          analysis: -0.12,
        },
        {
          groupId: '24',
          section: 'detail-oriented',
          analysis: 0.08,
        },
        {
          groupId: '25',
          section: 'adaptability',
          analysis: 2.24,
        },
        {
          groupId: '25',
          section: 'integrity',
          analysis: 1.68,
        },
        {
          groupId: '25',
          section: 'collaborative',
          analysis: 0.08,
        },
        {
          groupId: '25',
          section: 'results-oriented',
          analysis: -1.08,
        },
        {
          groupId: '25',
          section: 'customer-oriented',
          analysis: 0.04,
        },
        {
          groupId: '25',
          section: 'detail-oriented',
          analysis: -1.36,
        },
        {
          groupId: '26',
          section: 'adaptability',
          analysis: 2.36,
        },
        {
          groupId: '26',
          section: 'integrity',
          analysis: -0.4,
        },
        {
          groupId: '26',
          section: 'collaborative',
          analysis: -0.2,
        },
        {
          groupId: '26',
          section: 'results-oriented',
          analysis: -0.48,
        },
        {
          groupId: '26',
          section: 'customer-oriented',
          analysis: -0.32,
        },
        {
          groupId: '26',
          section: 'detail-oriented',
          analysis: -0.36,
        },
        {
          groupId: '27',
          section: 'adaptability',
          analysis: 0.33,
        },
        {
          groupId: '27',
          section: 'integrity',
          analysis: 0.06,
        },
        {
          groupId: '27',
          section: 'collaborative',
          analysis: -1.41,
        },
        {
          groupId: '27',
          section: 'results-oriented',
          analysis: 0.33,
        },
        {
          groupId: '27',
          section: 'customer-oriented',
          analysis: -0.48,
        },
        {
          groupId: '27',
          section: 'detail-oriented',
          analysis: 0.36,
        },
        {
          groupId: '28',
          section: 'adaptability',
          analysis: -0.36,
        },
        {
          groupId: '28',
          section: 'integrity',
          analysis: 0.12,
        },
        {
          groupId: '28',
          section: 'collaborative',
          analysis: 2.4,
        },
        {
          groupId: '28',
          section: 'results-oriented',
          analysis: -0.64,
        },
        {
          groupId: '28',
          section: 'customer-oriented',
          analysis: -0.32,
        },
        {
          groupId: '28',
          section: 'detail-oriented',
          analysis: -0.08,
        },
        {
          groupId: '29',
          section: 'adaptability',
          analysis: -0.32,
        },
        {
          groupId: '29',
          section: 'integrity',
          analysis: -1.6,
        },
        {
          groupId: '29',
          section: 'collaborative',
          analysis: -0.04,
        },
        {
          groupId: '29',
          section: 'results-oriented',
          analysis: 0.32,
        },
        {
          groupId: '29',
          section: 'customer-oriented',
          analysis: -0.04,
        },
        {
          groupId: '29',
          section: 'detail-oriented',
          analysis: -0.96,
        },
        {
          groupId: '3',
          section: 'adaptability',
          analysis: 1.64,
        },
        {
          groupId: '3',
          section: 'integrity',
          analysis: -1.08,
        },
        {
          groupId: '3',
          section: 'collaborative',
          analysis: 0.08,
        },
        {
          groupId: '3',
          section: 'results-oriented',
          analysis: -0.28,
        },
        {
          groupId: '3',
          section: 'customer-oriented',
          analysis: 0.12,
        },
        {
          groupId: '3',
          section: 'detail-oriented',
          analysis: -0.48,
        },
        {
          groupId: '30',
          section: 'adaptability',
          analysis: -0.16,
        },
        {
          groupId: '30',
          section: 'integrity',
          analysis: 0.36,
        },
        {
          groupId: '30',
          section: 'collaborative',
          analysis: 0,
        },
        {
          groupId: '30',
          section: 'results-oriented',
          analysis: -0.44,
        },
        {
          groupId: '30',
          section: 'customer-oriented',
          analysis: 1,
        },
        {
          groupId: '30',
          section: 'detail-oriented',
          analysis: 2.48,
        },
        {
          groupId: '31',
          section: 'adaptability',
          analysis: 2.04,
        },
        {
          groupId: '31',
          section: 'integrity',
          analysis: -1.48,
        },
        {
          groupId: '31',
          section: 'collaborative',
          analysis: -0.84,
        },
        {
          groupId: '31',
          section: 'results-oriented',
          analysis: 0.4,
        },
        {
          groupId: '31',
          section: 'customer-oriented',
          analysis: -0.52,
        },
        {
          groupId: '31',
          section: 'detail-oriented',
          analysis: -0.4,
        },
        {
          groupId: '32',
          section: 'adaptability',
          analysis: 0.04,
        },
        {
          groupId: '32',
          section: 'integrity',
          analysis: -0.33,
        },
        {
          groupId: '32',
          section: 'collaborative',
          analysis: -0.44,
        },
        {
          groupId: '32',
          section: 'results-oriented',
          analysis: 0.28,
        },
        {
          groupId: '32',
          section: 'customer-oriented',
          analysis: -0.17,
        },
        {
          groupId: '32',
          section: 'detail-oriented',
          analysis: -0.07,
        },
        {
          groupId: '33',
          section: 'adaptability',
          analysis: -0.2,
        },
        {
          groupId: '33',
          section: 'integrity',
          analysis: 3.04,
        },
        {
          groupId: '33',
          section: 'collaborative',
          analysis: 0.28,
        },
        {
          groupId: '33',
          section: 'results-oriented',
          analysis: 0.04,
        },
        {
          groupId: '33',
          section: 'customer-oriented',
          analysis: 0.08,
        },
        {
          groupId: '33',
          section: 'detail-oriented',
          analysis: 0.16,
        },
        {
          groupId: '34',
          section: 'adaptability',
          analysis: 0.52,
        },
        {
          groupId: '34',
          section: 'integrity',
          analysis: -0.28,
        },
        {
          groupId: '34',
          section: 'collaborative',
          analysis: -0.32,
        },
        {
          groupId: '34',
          section: 'results-oriented',
          analysis: 2.32,
        },
        {
          groupId: '34',
          section: 'customer-oriented',
          analysis: -0.28,
        },
        {
          groupId: '34',
          section: 'detail-oriented',
          analysis: 0.08,
        },
        {
          groupId: '35',
          section: 'adaptability',
          analysis: -0.04,
        },
        {
          groupId: '35',
          section: 'integrity',
          analysis: 3.08,
        },
        {
          groupId: '35',
          section: 'collaborative',
          analysis: 0.32,
        },
        {
          groupId: '35',
          section: 'results-oriented',
          analysis: -0.08,
        },
        {
          groupId: '35',
          section: 'customer-oriented',
          analysis: -0.12,
        },
        {
          groupId: '35',
          section: 'detail-oriented',
          analysis: 0.08,
        },
        {
          groupId: '36',
          section: 'adaptability',
          analysis: 0,
        },
        {
          groupId: '36',
          section: 'integrity',
          analysis: 0,
        },
        {
          groupId: '36',
          section: 'collaborative',
          analysis: 0,
        },
        {
          groupId: '36',
          section: 'results-oriented',
          analysis: 0,
        },
        {
          groupId: '36',
          section: 'customer-oriented',
          analysis: 0,
        },
        {
          groupId: '36',
          section: 'detail-oriented',
          analysis: 0,
        },
        {
          groupId: '37',
          section: 'adaptability',
          analysis: -0.06,
        },
        {
          groupId: '37',
          section: 'integrity',
          analysis: 1.2,
        },
        {
          groupId: '37',
          section: 'collaborative',
          analysis: 0.33,
        },
        {
          groupId: '37',
          section: 'results-oriented',
          analysis: -0.48,
        },
        {
          groupId: '37',
          section: 'customer-oriented',
          analysis: 0.21,
        },
        {
          groupId: '37',
          section: 'detail-oriented',
          analysis: -0.9,
        },
        {
          groupId: '38',
          section: 'adaptability',
          analysis: 3.16,
        },
        {
          groupId: '38',
          section: 'integrity',
          analysis: -1.4,
        },
        {
          groupId: '38',
          section: 'collaborative',
          analysis: -1.08,
        },
        {
          groupId: '38',
          section: 'results-oriented',
          analysis: 0.08,
        },
        {
          groupId: '38',
          section: 'customer-oriented',
          analysis: -0.92,
        },
        {
          groupId: '38',
          section: 'detail-oriented',
          analysis: -0.72,
        },
        {
          groupId: '39',
          section: 'adaptability',
          analysis: 0,
        },
        {
          groupId: '39',
          section: 'integrity',
          analysis: 0.2,
        },
        {
          groupId: '39',
          section: 'collaborative',
          analysis: 0.24,
        },
        {
          groupId: '39',
          section: 'results-oriented',
          analysis: 0,
        },
        {
          groupId: '39',
          section: 'customer-oriented',
          analysis: 3.16,
        },
        {
          groupId: '39',
          section: 'detail-oriented',
          analysis: 0.32,
        },
        {
          groupId: '4',
          section: 'adaptability',
          analysis: -1.14,
        },
        {
          groupId: '4',
          section: 'integrity',
          analysis: -0.48,
        },
        {
          groupId: '4',
          section: 'collaborative',
          analysis: 1.29,
        },
        {
          groupId: '4',
          section: 'results-oriented',
          analysis: -0.87,
        },
        {
          groupId: '4',
          section: 'customer-oriented',
          analysis: -0.21,
        },
        {
          groupId: '4',
          section: 'detail-oriented',
          analysis: -0.27,
        },
        {
          groupId: '40',
          section: 'adaptability',
          analysis: -1.72,
        },
        {
          groupId: '40',
          section: 'integrity',
          analysis: -0.44,
        },
        {
          groupId: '40',
          section: 'collaborative',
          analysis: -0.68,
        },
        {
          groupId: '40',
          section: 'results-oriented',
          analysis: 1.56,
        },
        {
          groupId: '40',
          section: 'customer-oriented',
          analysis: 0.72,
        },
        {
          groupId: '40',
          section: 'detail-oriented',
          analysis: -1.2,
        },
        {
          groupId: '41',
          section: 'adaptability',
          analysis: 0.84,
        },
        {
          groupId: '41',
          section: 'integrity',
          analysis: -0.36,
        },
        {
          groupId: '41',
          section: 'collaborative',
          analysis: 0.02,
        },
        {
          groupId: '41',
          section: 'results-oriented',
          analysis: -0.54,
        },
        {
          groupId: '41',
          section: 'customer-oriented',
          analysis: -0.46,
        },
        {
          groupId: '41',
          section: 'detail-oriented',
          analysis: -0.48,
        },
        {
          groupId: '42',
          section: 'adaptability',
          analysis: -0.32,
        },
        {
          groupId: '42',
          section: 'integrity',
          analysis: -0.12,
        },
        {
          groupId: '42',
          section: 'collaborative',
          analysis: 0.08,
        },
        {
          groupId: '42',
          section: 'results-oriented',
          analysis: 0.36,
        },
        {
          groupId: '42',
          section: 'customer-oriented',
          analysis: -0.48,
        },
        {
          groupId: '42',
          section: 'detail-oriented',
          analysis: 2.96,
        },
        {
          groupId: '43',
          section: 'adaptability',
          analysis: -1.89,
        },
        {
          groupId: '43',
          section: 'integrity',
          analysis: -0.18,
        },
        {
          groupId: '43',
          section: 'collaborative',
          analysis: -0.03,
        },
        {
          groupId: '43',
          section: 'results-oriented',
          analysis: -0.54,
        },
        {
          groupId: '43',
          section: 'customer-oriented',
          analysis: 0.15,
        },
        {
          groupId: '43',
          section: 'detail-oriented',
          analysis: -0.27,
        },
        {
          groupId: '44',
          section: 'adaptability',
          analysis: -0.02,
        },
        {
          groupId: '44',
          section: 'integrity',
          analysis: -0.48,
        },
        {
          groupId: '44',
          section: 'collaborative',
          analysis: 0.36,
        },
        {
          groupId: '44',
          section: 'results-oriented',
          analysis: 0.08,
        },
        {
          groupId: '44',
          section: 'customer-oriented',
          analysis: -0.1,
        },
        {
          groupId: '44',
          section: 'detail-oriented',
          analysis: -0.26,
        },
        {
          groupId: '45',
          section: 'adaptability',
          analysis: 0,
        },
        {
          groupId: '45',
          section: 'integrity',
          analysis: 2.12,
        },
        {
          groupId: '45',
          section: 'collaborative',
          analysis: 1.4,
        },
        {
          groupId: '45',
          section: 'results-oriented',
          analysis: -0.8,
        },
        {
          groupId: '45',
          section: 'customer-oriented',
          analysis: -0.12,
        },
        {
          groupId: '45',
          section: 'detail-oriented',
          analysis: -0.44,
        },
        {
          groupId: '46',
          section: 'adaptability',
          analysis: 2.36,
        },
        {
          groupId: '46',
          section: 'integrity',
          analysis: -0.6,
        },
        {
          groupId: '46',
          section: 'collaborative',
          analysis: -1.08,
        },
        {
          groupId: '46',
          section: 'results-oriented',
          analysis: 0.04,
        },
        {
          groupId: '46',
          section: 'customer-oriented',
          analysis: -0.08,
        },
        {
          groupId: '46',
          section: 'detail-oriented',
          analysis: -0.52,
        },
        {
          groupId: '47',
          section: 'adaptability',
          analysis: -0.64,
        },
        {
          groupId: '47',
          section: 'integrity',
          analysis: -0.04,
        },
        {
          groupId: '47',
          section: 'collaborative',
          analysis: -0.28,
        },
        {
          groupId: '47',
          section: 'results-oriented',
          analysis: -2.28,
        },
        {
          groupId: '47',
          section: 'customer-oriented',
          analysis: -0.36,
        },
        {
          groupId: '47',
          section: 'detail-oriented',
          analysis: -0.44,
        },
        {
          groupId: '48',
          section: 'adaptability',
          analysis: -0.34,
        },
        {
          groupId: '48',
          section: 'integrity',
          analysis: -0.11,
        },
        {
          groupId: '48',
          section: 'collaborative',
          analysis: 0.3,
        },
        {
          groupId: '48',
          section: 'results-oriented',
          analysis: -0.24,
        },
        {
          groupId: '48',
          section: 'customer-oriented',
          analysis: 0.03,
        },
        {
          groupId: '48',
          section: 'detail-oriented',
          analysis: -0.09,
        },
        {
          groupId: '49',
          section: 'adaptability',
          analysis: 0.04,
        },
        {
          groupId: '49',
          section: 'integrity',
          analysis: -1.48,
        },
        {
          groupId: '49',
          section: 'collaborative',
          analysis: -0.48,
        },
        {
          groupId: '49',
          section: 'results-oriented',
          analysis: -0.32,
        },
        {
          groupId: '49',
          section: 'customer-oriented',
          analysis: -0.84,
        },
        {
          groupId: '49',
          section: 'detail-oriented',
          analysis: -2.6,
        },
        {
          groupId: '5',
          section: 'adaptability',
          analysis: 0.02,
        },
        {
          groupId: '5',
          section: 'integrity',
          analysis: -0.26,
        },
        {
          groupId: '5',
          section: 'collaborative',
          analysis: -0.51,
        },
        {
          groupId: '5',
          section: 'results-oriented',
          analysis: 0.26,
        },
        {
          groupId: '5',
          section: 'customer-oriented',
          analysis: -0.14,
        },
        {
          groupId: '5',
          section: 'detail-oriented',
          analysis: -0.1,
        },
        {
          groupId: '50',
          section: 'adaptability',
          analysis: -0.64,
        },
        {
          groupId: '50',
          section: 'integrity',
          analysis: -0.04,
        },
        {
          groupId: '50',
          section: 'collaborative',
          analysis: -1.52,
        },
        {
          groupId: '50',
          section: 'results-oriented',
          analysis: -0.44,
        },
        {
          groupId: '50',
          section: 'customer-oriented',
          analysis: 0.08,
        },
        {
          groupId: '50',
          section: 'detail-oriented',
          analysis: -1.28,
        },
        {
          groupId: '51',
          section: 'adaptability',
          analysis: -0.12,
        },
        {
          groupId: '51',
          section: 'integrity',
          analysis: -0.04,
        },
        {
          groupId: '51',
          section: 'collaborative',
          analysis: -0.04,
        },
        {
          groupId: '51',
          section: 'results-oriented',
          analysis: 0.44,
        },
        {
          groupId: '51',
          section: 'customer-oriented',
          analysis: 0.16,
        },
        {
          groupId: '51',
          section: 'detail-oriented',
          analysis: -2.8,
        },
        {
          groupId: '52',
          section: 'adaptability',
          analysis: -0.1,
        },
        {
          groupId: '52',
          section: 'integrity',
          analysis: -0.18,
        },
        {
          groupId: '52',
          section: 'collaborative',
          analysis: -1.12,
        },
        {
          groupId: '52',
          section: 'results-oriented',
          analysis: 0.26,
        },
        {
          groupId: '52',
          section: 'customer-oriented',
          analysis: -0.08,
        },
        {
          groupId: '52',
          section: 'detail-oriented',
          analysis: -0.3,
        },
        {
          groupId: '53',
          section: 'adaptability',
          analysis: 0,
        },
        {
          groupId: '53',
          section: 'integrity',
          analysis: 0,
        },
        {
          groupId: '53',
          section: 'collaborative',
          analysis: 0,
        },
        {
          groupId: '53',
          section: 'results-oriented',
          analysis: 0,
        },
        {
          groupId: '53',
          section: 'customer-oriented',
          analysis: 0,
        },
        {
          groupId: '53',
          section: 'detail-oriented',
          analysis: 0,
        },
        {
          groupId: '54',
          section: 'adaptability',
          analysis: 0.12,
        },
        {
          groupId: '54',
          section: 'integrity',
          analysis: 0.24,
        },
        {
          groupId: '54',
          section: 'collaborative',
          analysis: 2.84,
        },
        {
          groupId: '54',
          section: 'results-oriented',
          analysis: 0.44,
        },
        {
          groupId: '54',
          section: 'customer-oriented',
          analysis: -0.12,
        },
        {
          groupId: '54',
          section: 'detail-oriented',
          analysis: 0,
        },
        {
          groupId: '6',
          section: 'adaptability',
          analysis: -0.52,
        },
        {
          groupId: '6',
          section: 'integrity',
          analysis: -1.08,
        },
        {
          groupId: '6',
          section: 'collaborative',
          analysis: -0.6,
        },
        {
          groupId: '6',
          section: 'results-oriented',
          analysis: 0.16,
        },
        {
          groupId: '6',
          section: 'customer-oriented',
          analysis: -1.08,
        },
        {
          groupId: '6',
          section: 'detail-oriented',
          analysis: 0.36,
        },
        {
          groupId: '7',
          section: 'adaptability',
          analysis: 0.48,
        },
        {
          groupId: '7',
          section: 'integrity',
          analysis: -0.6,
        },
        {
          groupId: '7',
          section: 'collaborative',
          analysis: 0.39,
        },
        {
          groupId: '7',
          section: 'results-oriented',
          analysis: -0.3,
        },
        {
          groupId: '7',
          section: 'customer-oriented',
          analysis: 0.09,
        },
        {
          groupId: '7',
          section: 'detail-oriented',
          analysis: -0.48,
        },
        {
          groupId: '8',
          section: 'adaptability',
          analysis: -2.56,
        },
        {
          groupId: '8',
          section: 'integrity',
          analysis: -0.36,
        },
        {
          groupId: '8',
          section: 'collaborative',
          analysis: 0.2,
        },
        {
          groupId: '8',
          section: 'results-oriented',
          analysis: -1,
        },
        {
          groupId: '8',
          section: 'customer-oriented',
          analysis: -0.36,
        },
        {
          groupId: '8',
          section: 'detail-oriented',
          analysis: 0.6,
        },
        {
          groupId: '9',
          section: 'adaptability',
          analysis: -0.04,
        },
        {
          groupId: '9',
          section: 'integrity',
          analysis: -0.8,
        },
        {
          groupId: '9',
          section: 'collaborative',
          analysis: -1.8,
        },
        {
          groupId: '9',
          section: 'results-oriented',
          analysis: 0.04,
        },
        {
          groupId: '9',
          section: 'customer-oriented',
          analysis: -0.36,
        },
        {
          groupId: '9',
          section: 'detail-oriented',
          analysis: -1.2,
        },
      ],
    },
  };

  constructor() {}

  ngOnInit(): void {}
}
